version: '3.8'

services:
    database:
        container_name: mysql_database
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - db_vol_dev:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DEV_DB_NAME}
            MYSQL_USER: ${DEV_DB_USER}
            MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
        ports:
            - 3306:3306
    
    api:
        container_name: rocket_api
        environment:
          - DATABASE_URL=mysql://${DEV_DB_USER}:${DEV_DB_PASSWORD}@database:3306/rust_db
        build: .
        ports:
            - 8000:8000
        command: cargo run
        volumes:
            - ./:/usr/src/app
        links:
          - database
        
volumes:
    db_vol_dev: